#! /usr/bin/env bash
#
# Post the cargo-llvm-cov report for a pull request as a comment.
#
# Usage:
#   ./contrib/coverage-comment.sh [coverage.json]
#
# The report is read from a JSON file produced by:
#   cargo llvm-cov --json --summary-only --output-path coverage.json
#
# When a comment from a previous run is found (matched by a hidden marker) it is
# edited in place instead of creating a new one, so each push updates the same
# coverage report.
#
# Environment (normally supplied by Forgejo Actions):
#   FORGEJO_TOKEN / GITHUB_TOKEN            token with write access to issues
#   FORGEJO_REPOSITORY / GITHUB_REPOSITORY  owner/repo
#   FORGEJO_SERVER_URL / GITHUB_SERVER_URL  Forgejo base URL
#   FORGEJO_EVENT_PATH / GITHUB_EVENT_PATH  path to the event webhook payload
#   FORGEJO_EVENT_NAME / GITHUB_EVENT_NAME  event that triggered the workflow
#   FORGEJO_WORKSPACE / GITHUB_WORKSPACE    checkout root, used to shorten paths
#   FORGEJO_RUN_ID / GITHUB_RUN_ID          workflow run id, linked in the report
#   COVERAGE_MIN_LINES                      threshold to report against (95)
#   COVERAGE_COMMENT_PRINT=1                print the report instead of posting

set -euo pipefail

readonly COVERAGE_JSON="${1:-coverage.json}"
readonly MARKER='<!-- forge-bot:coverage -->'
readonly THRESHOLD="${COVERAGE_MIN_LINES:-95}"

if [[ ! -f "$COVERAGE_JSON" ]]; then
    echo "coverage-comment: $COVERAGE_JSON not found; skipping" >&2
    exit 0
fi

for tool in jq curl awk; do
    command -v "$tool" >/dev/null 2>&1 || {
        echo "coverage-comment: $tool is required" >&2
        exit 1
    }
done

# Format a float with two decimals.
pct() {
    awk -v n="$1" 'BEGIN { printf "%.2f", n }'
}

read -r line_pct line_cov line_total \
    func_pct func_cov func_total \
    region_pct region_cov region_total <<<"$(
    jq -r '.data[0].totals
        | [.lines.percent, .lines.covered, .lines.count,
           .functions.percent, .functions.covered, .functions.count,
           .regions.percent, .regions.covered, .regions.count] | @tsv' \
        "$COVERAGE_JSON"
)"

if awk -v c="$line_pct" -v t="$THRESHOLD" 'BEGIN { exit !(c + 0 >= t + 0) }'; then
    verdict="✅ meets the ${THRESHOLD}% line-coverage threshold"
else
    verdict="❌ below the ${THRESHOLD}% line-coverage threshold"
fi

forge_url="${FORGEJO_SERVER_URL:-${GITHUB_SERVER_URL:-}}"
repo="${FORGEJO_REPOSITORY:-${GITHUB_REPOSITORY:-}}"
run_id="${FORGEJO_RUN_ID:-${GITHUB_RUN_ID:-}}"
workspace="${FORGEJO_WORKSPACE:-${GITHUB_WORKSPACE:-}}"
event_path="${FORGEJO_EVENT_PATH:-${GITHUB_EVENT_PATH:-}}"
event_name="${FORGEJO_EVENT_NAME:-${GITHUB_EVENT_NAME:-}}"

# Prefer the public repository URL from the event payload over the runner's
# internal server URL, which may point at a non-public address/port.
run_base="${forge_url%/}/$repo"
if [[ -n "$event_path" && -f "$event_path" ]]; then
    repo_html_url="$(jq -r '.repository.html_url // empty' "$event_path" 2>/dev/null || true)"
    if [[ -n "$repo_html_url" ]]; then
        run_base="${repo_html_url%/}"
    fi
fi

body_file="$(mktemp)"
trap 'rm -f "$body_file"' EXIT

{
    printf '%s\n' "$MARKER"
    printf '## Test coverage\n\n'
    printf '**Lines: %s%%** (%s/%s) — %s\n\n' \
        "$(pct "$line_pct")" "$line_cov" "$line_total" "$verdict"
    printf '| Metric | Coverage | Covered / Total |\n'
    printf '| --- | ---: | ---: |\n'
    printf '| Lines | %s%% | %s / %s |\n' \
        "$(pct "$line_pct")" "$line_cov" "$line_total"
    printf '| Functions | %s%% | %s / %s |\n' \
        "$(pct "$func_pct")" "$func_cov" "$func_total"
    printf '| Regions | %s%% | %s / %s |\n' \
        "$(pct "$region_pct")" "$region_cov" "$region_total"
    printf '\n<details>\n<summary>Per-file breakdown (%s files)</summary>\n\n' \
        "$(jq '.data[0].files | length' "$COVERAGE_JSON")"
    printf '| File | Lines | Functions |\n'
    printf '| --- | ---: | ---: |\n'
    while IFS=$'\t' read -r file lp lc lt fp; do
        rel="$file"
        if [[ -n "$workspace" && "$file" == "$workspace"/* ]]; then
            rel="${file#"$workspace"/}"
        fi
        printf '| `%s` | %s%% (%s/%s) | %s%% |\n' \
            "$rel" "$(pct "$lp")" "$lc" "$lt" "$(pct "$fp")"
    done < <(
        jq -r '.data[0].files[]
            | [.filename, .summary.lines.percent, .summary.lines.covered,
               .summary.lines.count, .summary.functions.percent] | @tsv' \
            "$COVERAGE_JSON" | sort -t $'\t' -k2 -n
    )
    printf '\n</details>\n'
    if [[ -n "$run_id" && -n "$run_base" ]]; then
        printf '\n_Generated by `cargo llvm-cov` in [workflow run %s](%s/actions/runs/%s)._\n' \
            "$run_id" "$run_base" "$run_id"
    fi
} >"$body_file"

if [[ "${COVERAGE_COMMENT_PRINT:-0}" == "1" ]]; then
    cat "$body_file"
    exit 0
fi

token="${FORGEJO_TOKEN:-${GITHUB_TOKEN:-}}"

if [[ -z "$forge_url" || -z "$repo" || -z "$token" ]]; then
    echo "coverage-comment: forge credentials missing; printing report only" >&2
    cat "$body_file"
    exit 0
fi

if [[ "$event_name" != "pull_request" && "$event_name" != "pull_request_target" ]]; then
    echo "coverage-comment: '$event_name' is not a pull request event; skipping" >&2
    exit 0
fi

if [[ -z "$event_path" || ! -f "$event_path" ]]; then
    echo "coverage-comment: event payload not found; skipping" >&2
    exit 0
fi

number="$(jq -r '.pull_request.number // .number // empty' "$event_path")"
if [[ -z "$number" ]]; then
    echo "coverage-comment: no pull request number in event payload; skipping" >&2
    exit 0
fi

readonly AUTH="Authorization: token $token"
readonly COMMENTS_URL="${forge_url%/}/api/v1/repos/$repo/issues/$number/comments"

comments_file="$(mktemp)"
trap 'rm -f "$body_file" "$comments_file"' EXIT

curl -fsS -H "$AUTH" "$COMMENTS_URL?limit=100" -o "$comments_file"
existing_id="$(
    jq -r --arg marker "$MARKER" \
        '.[] | select((.body // "") | contains($marker)) | .id' \
        "$comments_file" | head -n1 || true
)"

payload="$(jq -Rs '{body: .}' <"$body_file")"

if [[ -n "$existing_id" ]]; then
    curl -fsS -X PATCH -H "$AUTH" -H 'Content-Type: application/json' \
        -d "$payload" \
        "${forge_url%/}/api/v1/repos/$repo/issues/comments/$existing_id" >/dev/null
    echo "coverage-comment: updated comment $existing_id on $repo#$number"
else
    curl -fsS -X POST -H "$AUTH" -H 'Content-Type: application/json' \
        -d "$payload" "$COMMENTS_URL" >/dev/null
    echo "coverage-comment: posted coverage report on $repo#$number"
fi
